"""unique lower(username)

Revision ID: 0967a4fb6032
Revises: 837c82c3fa1e
Create Date: 2025-11-10 17:49:56.586024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0967a4fb6032'
down_revision: Union[str, Sequence[str], None] = '837c82c3fa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_app_user_username'), 'app_user', type_='unique')
    op.create_index('uq_user_username_lower', 'app_user', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_username_lower', table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_username'), 'app_user', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
