"""use list for open_days

Revision ID: 837c82c3fa1e
Revises: c66ebdb55a03
Create Date: 2025-11-06 13:46:06.577181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '837c82c3fa1e'
down_revision: Union[str, Sequence[str], None] = 'c66ebdb55a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('open_days', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text('ARRAY[0,1,2,3,4,5,6]::int[]'), nullable=False))
    op.drop_column('week', 'open_days_mask')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('open_days_mask', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('week', 'open_days')
    # ### end Alembic commands ###
