"""Create schemas and update models

Revision ID: 9c9b569168ea
Revises: f216a550aa09
Create Date: 2025-11-01 12:28:20.572535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9b569168ea'
down_revision: Union[str, Sequence[str], None] = 'f216a550aa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('username', sa.String(length=200), nullable=False))
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_username'), 'app_user', ['username'])
    op.drop_column('app_user', 'is_active')
    op.drop_column('app_user', 'email')
    op.add_column('shift', sa.Column('weekday', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_shift_user_id_week_id_dow'), table_name='shift')
    op.create_index('ix_shift_user_id_week_id_dow', 'shift', ['user_id', 'week_id', 'weekday'], unique=False)
    op.drop_constraint(op.f('uq_shift_slot'), 'shift', type_='unique')
    op.create_unique_constraint('uq_shift_slot', 'shift', ['user_id', 'week_id', 'weekday', 'start_time', 'end_time'])
    op.drop_column('shift', 'day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_shift_slot', 'shift', type_='unique')
    op.create_unique_constraint(op.f('uq_shift_slot'), 'shift', ['user_id', 'week_id', 'day_of_week', 'start_time', 'end_time'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_shift_user_id_week_id_dow', table_name='shift')
    op.create_index(op.f('ix_shift_user_id_week_id_dow'), 'shift', ['user_id', 'week_id', 'day_of_week'], unique=False)
    op.drop_column('shift', 'weekday')
    op.add_column('app_user', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('app_user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_app_user_username'), 'app_user', type_='unique')
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.drop_column('app_user', 'username')
    # ### end Alembic commands ###
