"""replace username with email

Revision ID: c31bcd7719b4
Revises: 1553844918e2
Create Date: 2025-11-11 15:55:04.653443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31bcd7719b4'
down_revision: Union[str, Sequence[str], None] = '1553844918e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('email', sa.String(length=254), nullable=False))
    op.drop_constraint(op.f('uq_app_user_username'), 'app_user', type_='unique')
    op.create_index('uq_user_email_ci', 'app_user', [sa.literal_column('lower(email)')], unique=True)
    op.drop_column('app_user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index('uq_user_email_ci', table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_username'), 'app_user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('app_user', 'email')
    # ### end Alembic commands ###
