"""fix shift assignment fk conflicts

Revision ID: c66ebdb55a03
Revises: b99f4fe421ba
Create Date: 2025-11-05 22:46:44.568102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ebdb55a03'
down_revision: Union[str, Sequence[str], None] = 'b99f4fe421ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
