"""MVP modeling

Revision ID: f216a550aa09
Revises: f1a39fd7e6aa
Create Date: 2025-10-28 22:55:51.689656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f216a550aa09'
down_revision: Union[str, Sequence[str], None] = 'f1a39fd7e6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('employee',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_employee_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_employee_user_id_id'))
    )
    op.create_index('ix_employee_user_id_active', 'employee', ['user_id', 'active'], unique=False)
    op.create_index('ix_employee_user_id_name', 'employee', ['user_id', 'name'], unique=False)
    op.create_table('week',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('open_days_mask', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('EXTRACT(DOW FROM start_date) = 1', name=op.f('ck_week_start_is_monday')),
    sa.CheckConstraint('open_days_mask BETWEEN 0 AND 127', name=op.f('ck_week_open_days_mask_range')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_week_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_week')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_week_user_id_id')),
    sa.UniqueConstraint('user_id', 'start_date', name=op.f('uq_week_user_id_start_date'))
    )
    op.create_index('ix_week_user_id_approved', 'week', ['user_id', 'approved'], unique=False)
    op.create_table('availability',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_availability_availability_time_ok')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_availability_weekday_range')),
    sa.ForeignKeyConstraint(['user_id', 'employee_id'], ['employee.user_id', 'employee.id'], name='fk_availability_employee_user_scoped', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability')),
    sa.UniqueConstraint('user_id', 'employee_id', 'weekday', 'start_time', 'end_time', name='uq_availability_slot')
    )
    op.create_index('ix_availability_user_employee_weekday', 'availability', ['user_id', 'employee_id', 'weekday'], unique=False)
    op.create_table('shift',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('min_staff', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_shift_dow_range')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_shift_no_overnight_for_now')),
    sa.CheckConstraint('min_staff >= 1', name=op.f('ck_shift_min_staff_positive')),
    sa.ForeignKeyConstraint(['user_id', 'week_id'], ['week.user_id', 'week.id'], name='fk_shift_week_user_scoped', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_shift_user_id_id')),
    sa.UniqueConstraint('user_id', 'week_id', 'day_of_week', 'start_time', 'end_time', name='uq_shift_slot')
    )
    op.create_index('ix_shift_user_id_week_id_dow', 'shift', ['user_id', 'week_id', 'day_of_week'], unique=False)
    op.create_table('shift_assignment',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'employee_id'], ['employee.user_id', 'employee.id'], name='fk_assignment_employee_user_scoped', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'shift_id'], ['shift.user_id', 'shift.id'], name='fk_assignment_shift_user_scoped', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignment')),
    sa.UniqueConstraint('user_id', 'shift_id', 'employee_id', name='uq_assignment_unique')
    )
    op.create_index('ix_assignment_user_employee', 'shift_assignment', ['user_id', 'employee_id'], unique=False)
    op.create_index('ix_assignment_user_shift', 'shift_assignment', ['user_id', 'shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_user_shift', table_name='shift_assignment')
    op.drop_index('ix_assignment_user_employee', table_name='shift_assignment')
    op.drop_table('shift_assignment')
    op.drop_index('ix_shift_user_id_week_id_dow', table_name='shift')
    op.drop_table('shift')
    op.drop_index('ix_availability_user_employee_weekday', table_name='availability')
    op.drop_table('availability')
    op.drop_index('ix_week_user_id_approved', table_name='week')
    op.drop_table('week')
    op.drop_index('ix_employee_user_id_name', table_name='employee')
    op.drop_index('ix_employee_user_id_active', table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
